
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: gaming-deploy
  labels:
    app: game-app
    env: prod
spec:
  replicas: 3
 
  selector:
    matchLabels:
      app: game-app
      env: prod
  template:
    metadata: 
      labels:
        app: game-app
        env: prod
        version: v2_vc

    spec:
      containers: 
      - name: gamesite-container
        image: anirudhreddyk/argocd-project:24
        ports:
        - containerPort: 8080
